name: "Orangefox Recovery"
description: "Building OrangeFox Recovery Using Github Action"
author: "AnGgIt86"

branding:
  icon: 'terminal'
  color: 'gray-dark'

inputs:
  FOX_SYNC:
    description: "Source On OrangeFox Recovery"
    required: false
    default: "https://gitlab.com/OrangeFox/sync.git"
  FOX_SYNC_BRANCH:
    description: "Branch On Orangefox For Sync"
    required: true
    default: "12.1"
  KERNEL_TREE:
    description: 'Kernel Tree On Your Device'
    required: false
    default: ''
  KERNEL_BRANCH:
    description: 'Branch On Your Kernel Tree'
    required: false
    default: ''
  KERNEL_PATH:
    description: 'Path On Your Kernel Directory'
    required: false
    default: 'kernel/vivo/1938'
  DEVICE_TREE:
    description: 'OrangeFox Device Tree'
    required: true
    default: 'https://github.com/UntuKemeng/ORF_device_vivo_1938'
  DEVICE_TREE_BRANCH:
    description: 'OrangeFox Device Tree Branch'
    required: true
    default: '12.1'
  DEVICE_PATH:
    description: 'Specify Your Device Path'
    required: true
    default: 'device/vivo/1938'
  DEVICE_NAME:
    description: 'Specify Your Device Codename'
    required: true
    default: '1938'
  BUILD_TARGET:
    description: 'Specify Your Build Target [boot, recovery, vendorboot'
    required: true
    default: 'recovery'
  COMMON_TREE:
    description: 'Common Tree On Your Device'
    required: false
    default: ''
  COMMON_BRANCH:
    description: 'Branch On Your Common Tree'
    required: false
    default: ''
  COMMON_PATH:
    description: 'Path On Your Common Directory'
    required: false
    default: 'common/vivo/1938'
  TG_CHAT_ID:
    description: 'Telegram Chat ID'
    required: false
    default: ''
  TG_TOKEN:
    description: 'Telegram Bot Token'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:

    - name: 🗑️ Clean-up
      uses: rokibhasansagar/slimhub_actions@main

    - name: 💽 Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 20

    - name: 🏢 Build Environment
      shell: bash
      run: |
        sudo cp proprietary/* /usr/bin
        sudo apt install aria2 figlet -y
        git clone https://github.com/akhilnarang/scripts.git -b master .sc
        sudo bash .sc/setup/android_build_env.sh

    - name: 🎡 Set-up Manifest Sync
      shell: bash
      env:
        TG_CHAT_ID: ${{ inputs.TG_CHAT_ID }}
        TG_TOKEN: ${{ inputs.TG_TOKEN }}
      run: |
        source config.sh
        echo -e ${cya} "Sync OrangeFox Recovery..."
        mkdir -p ${GITHUB_WORKSPACE}/OrangeFox && cd ${GITHUB_WORKSPACE}/OrangeFox
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git clone ${{ inputs.FOX_SYNC }} && cd sync
        ./orangefox_sync.sh --branch ${{ inputs.FOX_SYNC_BRANCH }} --path ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}
        cp -r ${GITHUB_WORKSPACE}/maintainer.png ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}/bootable/recovery/gui/theme/portrait_hdpi/images/Default/About
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}
        if [[ ! -d bootable/recovery/gui/theme ]]; then
            echo -e ${cya} "Adding Theme..."
            git clone https://gitlab.com/OrangeFox/misc/theme.git bootable/recovery/gui/theme
        fi
        if [[ ! -z "${{ inputs.KERNEL_TREE }}" ]]; then
            echo -e ${cya} "Clonning Kernel Tree..."
            git clone ${{ inputs.KERNEL_TREE }} -b ${{ inputs.KERNEL_BRANCH }} ${{ inputs.KERNEL_PATH }}
        fi
        if [[ ! -z "${{ inputs.COMMON_TREE }}" ]]; then
            echo -e ${cya} "Clonning Common Tree..."
            git clone ${{ inputs.COMMON_TREE }} -b ${{ inputs.COMMON_BRANCH }} ${{ inputs.COMMON_PATH }}
        fi
        if [[ ! -z "${{ inputs.DEVICE_TREE }}" ]]; then
            echo -e ${cya} "Clonning Device Tree..."
            git clone ${{ inputs.DEVICE_TREE }} -b ${{ inputs.DEVICE_TREE_BRANCH }} ${{ inputs.DEVICE_PATH }}
        fi

    - name: 🦊 Building OrangeFox
      shell: bash
      env:
        TG_CHAT_ID: ${{ inputs.TG_CHAT_ID }}
        TG_TOKEN: ${{ inputs.TG_TOKEN }}
        FOX_BRANCH: ${{ inputs.FOX_SYNC_BRANCH }}
        CODENAME: ${{ inputs.DEVICE_NAME }}
      run: |
        set +e
        source config.sh
        timeStart
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}
        echo -e ${cya} "##########################################"
        echo -e ${cya} "$(figlet "OrageFox")"
        echo -e ${cya} "##########################################"
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        BUILDLOG="${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}/build.log"
        DEVICE=$(grep "PRODUCT_BRAND :=" ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}/${{ inputs.DEVICE_PATH }}/twrp_*.mk -m 1 | cut -d = -f 2)
        set -e
        build_message "lunch twrp_${{ inputs.DEVICE_NAME }}-eng"
        lunch twrp_${{ inputs.DEVICE_NAME }}-eng
        sleep 5
        build_message "🛠️ Building..."
        mkfifo -m 644 reading
        tee -a ${BUILDLOG} < reading & progress & mka adbd ${{ inputs.BUILD_TARGET }}image -j$(nproc --all) > reading
        retVal=$?
        timeEnd
        statusBuild

    # - name: 📝 Set Release Properties
      # shell: bash
      # run: |
        # echo "BUILD_DATE=$(TZ=Asia/Jakarta date +%Y%m%d)" >> $GITHUB_ENV
        # cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}

    - name: 📤 Upload OrangeFox
      shell: bash
      env:
        TG_CHAT_ID: ${{ inputs.TG_CHAT_ID }}
        TG_TOKEN: ${{ inputs.TG_TOKEN }}
        FOX_BRANCH: ${{ inputs.FOX_SYNC_BRANCH }}
        CODENAME: ${{ inputs.DEVICE_NAME }}
      run: |
        source config.sh
        echo -e ${cya} "============================"
        echo -e ${cya} "Uploading the Build..."
        echo -e ${cya} "============================"
        TIMEOUT=20160
        FILENAME=${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}/out/target/product/${{ inputs.DEVICE_NAME }}/OrangeFox*.zip
        DEVICE=$(grep "PRODUCT_BRAND :=" ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.FOX_SYNC_BRANCH }}/${{ inputs.DEVICE_PATH }}/twrp_*.mk -m 1 | cut -d = -f 2)
        transfer wet $FILENAME > link.txt  || { echo -e ${red} "Failed Upload To transfer" }
        curl -T $FILENAME https://oshi.at/${FILENAME}/${TIMEOUT} > mirror.txt || { echo -e ${red} "Failed Upload To oshi.at" }
        DL_LINK=$(cat link.txt | grep Download | cut -d\  -f3)
        MIRROR_LINK=$(cat mirror.txt | grep Download | cut -d\  -f1)
        post_build
